metricbeat.modules:
  - module: system
    metricsets: ["core", "cpu", "load", "diskio", "memory", "network", "process", "socket"]
    period: 30s
  - module: elasticsearch
    metricsets: ["ccr", "enrich", "cluster_stats", "index", "index_recovery", "index_summary", "ml_job", "node_stats", "shard"]
    hosts: ["http://localhost:9200"]
    xpack.enabled: true
    period: 30s

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_labels: { labels: { build_id: '${build_id}' } }

tags: ['bench', 'gcp', '${client_name}']

output.elasticsearch:
  hosts: ["${reporting_elasticsearch_url}"]
  username: '${reporting_elasticsearch_username}'
  password: '${reporting_elasticsearch_password}'
