# See: https://github.com/hashicorp/terraform-github-actions/tree/master/examples

name: 'Terraform'

on:
  push:
    branches:
      - github-actions
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_ACTIONS: true

jobs:
  terraform:
    name: Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform/gcp'
      - name: Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/gcp'
      - name: Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'terraform/gcp'
  yaml:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sudo apt-get install python3-setuptools --yes --quiet
      - run: sudo python3 -m pip install --no-cache-dir --install-option="--install-scripts=/usr/local/bin" yamllint
      - name: Check
        run: >
            yamllint terraform/
            --strict
            --config-data '{ "extends":"default", "rules": {"document-start":"disable", "line-length":"disable", "braces":"disable", "colons":"disable"} }'
